packages:
  - 'apps/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - 'bcrypt'
  - 'esbuild'
  - 'nice-napi'
  - 'sharp'

minimumReleaseAge: 1440

allowBuilds:
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  sharp: true
