// src/config/env/env.defaults.ts
import type {
  LogFormat,
  LogLevel,
  NodeEnv,
  SessionCookieSameSite,
  StorageDriver,
} from './env.types';

export const ENV_DEFAULTS = {
  NODE_ENV: 'development' satisfies NodeEnv,
  APP_NAME: 'nest-api',
  APP_VERSION: '26.2',
  APP_HOST: '0.0.0.0',
  APP_PORT: 3000,
  FRONTEND_PUBLIC_URL: 'http://localhost:5173',
  TRUST_PROXY: false,

  API_ROUTE_PREFIX: 'api',
  API_VERSION: 'v1',

  PAGINATION_DEFAULT_PAGE: 1,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,

  JWT_ACCESS_TOKEN_EXPIRES_IN: '30m',
  JWT_REFRESH_TOKEN_EXPIRES_IN: '7d',
  JWT_REFRESH_TOKEN_COOKIE_NAME: 'refresh_token',
  PASSWORD_BCRYPT_SALT_ROUNDS: 10,

  CORS_ALLOWED_ORIGINS: ['http://localhost:5173'] as string[],
  CORS_CREDENTIALS: true,
  RATE_LIMIT_TTL_SECONDS: 60,
  RATE_LIMIT_MAX_REQUESTS: 100,
  THROTTLE_TTL_SECONDS: 60,
  THROTTLE_LIMIT: 20,

  DB_HOST: 'localhost',
  DB_PORT: 5432,
  DB_NAME: 'nest_api',
  DB_USERNAME: 'postgres',
  DB_PASSWORD: 'postgres',
  DB_SCHEMA: 'public',
  DB_SYNCHRONIZE: false,
  DB_DROP_SCHEMA: false,
  DB_LOGGING: false,
  DB_SSL: false,
  DB_MAX_CONNECTIONS: 10,
  DB_IDLE_TIMEOUT_MS: 30000,
  DB_CONNECTION_TIMEOUT_MS: 5000,
  DB_RUN_MIGRATIONS: false,
  DB_ADMIN_DATABASE: 'postgres',

  REDIS_HOST: 'localhost',
  REDIS_PORT: 6379,
  REDIS_DB: 0,
  REDIS_TTL_SECONDS: 3600,
  REDIS_KEY_PREFIX: 'nest-api',
  REDIS_MAX_RETRIES: 5,
  REDIS_CONNECT_TIMEOUT_MS: 10000,

  QUEUE_PREFIX: 'queue',
  QUEUE_DEFAULT_ATTEMPTS: 3,
  QUEUE_DEFAULT_BACKOFF_MS: 5000,

  SMTP_PORT: 587,
  SMTP_FROM_EMAIL: 'noreply@example.com',
  SMTP_FROM_NAME: 'Nest API',
  SMTP_SECURE: false,

  STORAGE_DRIVER: 'local' satisfies StorageDriver,
  STORAGE_LOCAL_ROOT_DIR: 'uploads',
  STORAGE_PUBLIC_PATH: 'media',
  AWS_S3_REGION: 'us-east-1',
  AWS_S3_FORCE_PATH_STYLE: false,
  AWS_S3_SIGNATURE_VERSION: 'v4',
  FILE_MAX_SIZE_BYTES: 5242880,
  FILE_ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/png',
    'image/webp',
  ] as string[],
  FILE_MAX_FILES_PER_REQUEST: 3,

  LOG_LEVEL: 'info' satisfies LogLevel,
  LOG_FORMAT: 'pretty' satisfies LogFormat,
  LOG_COLORIZE: true,
  LOG_TIMESTAMP: true,
  LOG_FILE_PATH: 'logs/app.log',
  LOG_MAX_SIZE_BYTES: 10485760,
  LOG_MAX_FILES: 7,
  SENTRY_TRACES_SAMPLE_RATE: 0,
  METRICS_ENABLED: false,
  METRICS_PATH: 'metrics',

  SWAGGER_ENABLED: true,
  SWAGGER_PATH: 'docs',
  SWAGGER_TITLE: 'Nest API',
  SWAGGER_DESCRIPTION: 'REST API documentation',
  SWAGGER_VERSION: 'v1',
  HEALTH_CHECKS_ENABLED: true,
  HEALTH_CHECK_PATH: 'health',
  HEALTH_CHECK_DETAILS_ENABLED: false,
  COMPRESSION_ENABLED: true,
  COMPRESSION_THRESHOLD_BYTES: 1024,
  COMPRESSION_LEVEL: 6,
  CACHE_ENABLED: false,
  CACHE_TTL_SECONDS: 60,

  GOOGLE_OAUTH_CALLBACK_ROUTE: 'auth/google/callback',
  STRIPE_CURRENCY: 'usd',

  REQUEST_TIMEOUT_MS: 30000,
  REQUEST_BODY_LIMIT_BYTES: 10485760,
  RESPONSE_VALIDATION_ENABLED: false,
  SESSION_MAX_AGE_MS: 86400000,
  SESSION_COOKIE_SECURE: false,
  SESSION_COOKIE_HTTP_ONLY: true,
  SESSION_COOKIE_SAME_SITE: 'lax' satisfies SessionCookieSameSite,

  DEBUG_ENABLED: false,
  VALIDATION_ERRORS_VISIBLE: false,
} as const;

export const DEVELOPMENT_SECRET_DEFAULTS = {
  JWT_ACCESS_TOKEN_SECRET: 'development-access-secret-change-me',
  JWT_REFRESH_TOKEN_SECRET: 'development-refresh-secret-change-me',
  SESSION_SECRET: 'development-session-secret-change-me',
} as const;
